### ISSUE TITLE
vpn-slice exits with error  (and does not work) unless I `--disable-ipv6`

### ISSUE THREAD

**Issue by simonheb** [dlenski/vpn-slice#154]
I understand that ipv6 support has to be considered beta.  Still, I wanted to report the following behavior when I use `openconnect` (with `--protocol=gp`) and `-s 'vpn-slice -v cluster.url.org'`)

 ```
WARNING: IPv6 address or netmask set. Support for IPv6 in vpn-slice should be considered BETA-QUALITY.
WARNING: IPv6 address or netmask set. Support for IPv6 in vpn-slice should be considered BETA-QUALITY.
Blocked incoming traffic from VPN interface with iptables.
RTNETLINK answers: Invalid argument
Traceback (most recent call last):
  File "/home/simon/vpn/bin/vpn-slice", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/simon/vpn/lib/python3.12/site-packages/vpn_slice/__main__.py", line 647, in main
    do_connect(env, args)
  File "/home/simon/vpn/lib/python3.12/site-packages/vpn_slice/__main__.py", line 218, in do_connect
    providers.route.add_address(env.tundev, env.myaddr6)
  File "/home/simon/vpn/lib/python3.12/site-packages/vpn_slice/linux.py", line 81, in add_address
    self._iproute(flag, 'address', 'add', address, dev=device)
  File "/home/simon/vpn/lib/python3.12/site-packages/vpn_slice/linux.py", line 50, in _iproute
    subprocess.check_call(cl)
  File "/usr/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/sbin/ip', '-6', 'address', 'add', '2001:???:???:???::???/128', 'dev', 'tun0']' returned non-zero exit status 2.
Script 'vpn/bin/vpn-slice -v cluster.url.org' returned error 1
Using vhost-net for tun acceleration, ring size 32

```
(??? in IP added by me)

everything works like a charm if I `--disable-ipv6`.

I'm unsure which configurational details would be interesting for debugging this. Happy to provide any info on request.

**Comment by gmacon** [comment]
This is reporting a failure from `/usr/sbin/ip`. The underlying error message is

```
RTNETLINK answers: Invalid argument
```

Are you sure IPv6 is enabled on your system?

**Comment by simonheb** [comment]
thanks for the quick reply and the explanation. I had (apparently incorrectly) assumed that ipv6 would be on because I am using a relatively fresh ubuntu 24.04 install. I wonder if my playing around with vpn-slice disabled it.

My reading of this `ip -a` now is that ipv6 is off on my system.

```
$ ip a 
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host noprefixroute 
       valid_lft forever preferred_lft forever
2: wlp0s20f3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1270 qdisc noqueue state UP group default qlen 1000
    link/ether 84:5c:f3:93:ab:ca brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.68/24 brd 192.168.0.255 scope global dynamic noprefixroute wlp0s20f3
       valid_lft 68052sec preferred_lft 68052sec
```

If that explains the error I'm getting. Thanks a lot for your assistance.
