### ISSUE TITLE
KeyError: 'network6' when called with -I without INTERNAL_IP6_ADDRESS

### ISSUE THREAD

**Issue by lkrms** [dlenski/vpn-slice#21]
When connecting to a GlobalConnect VPN that doesn't issue IPv6 addresses, `vpn-slice -IS` fails with the following stack trace:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/vpn_slice/util.py", line 17, in __getattr__
    return self[k]
KeyError: 'network6'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/vpn-slice", line 11, in <module>
    load_entry_point('vpn-slice==0.9.1', 'console_scripts', 'vpn-slice')()
  File "/usr/local/lib/python3.6/dist-packages/vpn_slice/main.py", line 340, in main
    p, args, env = parse_args_and_env()
  File "/usr/local/lib/python3.6/dist-packages/vpn_slice/main.py", line 333, in parse_args_and_env
    if env.network6: args.subnets.append(env.network6)
  File "/usr/local/lib/python3.6/dist-packages/vpn_slice/util.py", line 19, in __getattr__
    raise AttributeError(*e.args)
AttributeError: network6
Script 'vpn-slice -IS' returned error 1
User cancelled (SIGINT/SIGTERM); exiting.
```

The code depends on a dictionary key (`network6`) that isn't added unless `INTERNAL_IP6_ADDRESS` is in the environment.

PR with a fix incoming.

**Comment by dlenski** [comment]
Thanks for this excellent bug report.

For consistency between IPv4 and IPv6 handling… I have a slight preference for a different solution, which is to ensure that `env.network6` is always populated (with `None` by default) just like `env.network` is, so I've committed that instead of your PR.

**Comment by lkrms** [comment]
Thanks. That delivers a much better result than my PR.
