### ISSUE TITLE
File "/usr/local/bin/vpn-slice", line 8, in <module>

### ISSUE THREAD

**Issue by FernandoMiguel** [dlenski/vpn-slice#32]
upgraded from `vpn-slice 0.9.1` to `vpn-slice-0.11` with 
`pip3 install https://github.com/dlenski/vpn-slice/archive/master.zip`

```sh
$ vpn-slice --version
Traceback (most recent call last):
  File "/usr/local/bin/vpn-slice", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/vpn_slice/main.py", line 397, in main
    providers = get_default_providers()
  File "/usr/local/lib/python3.7/site-packages/vpn_slice/main.py", line 44, in get_default_providers
    hosts = PosixHostsFileProvider(),
  File "/usr/local/lib/python3.7/site-packages/vpn_slice/posix.py", line 67, in __init__
    super().__init__('/etc/hosts')
  File "/usr/local/lib/python3.7/site-packages/vpn_slice/posix.py", line 49, in __init__
    raise OSError('Cannot read/write {}'.format(path))
OSError: Cannot read/write /etc/hosts
```

**Comment by jhall39** [comment]
I have this problem with my Raspberry Pi. Additionally, if I try to use it with sudo I get:
`Traceback (most recent call last):
  File "/home/pi/.local/bin/vpn-slice", line 6, in <module>
    from vpn_slice.__main__ import main
ModuleNotFoundError: No module named 'vpn_slice'
`

**Comment by doomedraven** [comment]
is easy to fix, i will submit pr in a bit

**Comment by doomedraven** [comment]
check the PR it works just fine for version and 

```
─± python3
Python 3.7.6 (default, Dec 30 2019, 19:38:28)
>>> from vpn_slice.__main__ import main
>>>
```

```
╰─± vpn-slice -V
vpn-slice 0.12
```
